services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      sql:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
#  aspire-dashboard:
#    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
#    environment:
#      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
#    ports:
#      - "18888:18888"
  redis_vector:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"     # Expose Redis Stack on a different host port
      - "8001:8001"     # Optional: RedisInsight UI

    volumes:
      - redis_vector_data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
#      - REDIS_ARGS=--requirepass yourpassword
    
volumes:
  redis-data:
  sql-data:
  redis_vector_data: